#!/usr/bin/env python3
"""Generate site/firmware/versions.json from the board registry + GitHub Releases.

Merges the human-curated registry (site/boards.json: label + photo per board) with the
per-board `<board>-<version>.factory.bin` assets attached to the repo's GitHub Releases,
newest-first. The flasher (site/flash/index.html) fetches the result. Runs in CI (needs
GH_TOKEN + GITHUB_REPOSITORY in the env). Validated end-to-end at release #1.

  python .github/scripts/gen_versions_json.py --registry site/boards.json \
      --out site/firmware/versions.json [--url-prefix ../firmware]

Without --url-prefix, url = the Release asset download URL. With it (the Pages deploy copies
bins into site/firmware/), url = "<prefix>/<filename>" — same-origin, no CORS dependency.
"""
import argparse, json, os, re, sys, urllib.request

API = "https://api.github.com"
# <board-id>-<version>.factory.bin — splits at the LAST dash, so the version must be dash-free
# (our scheme is "0.1"). A dashed version like "0.1-rc1" would mis-split and be silently skipped.
ASSET_RE = re.compile(r"^(?P<id>.+)-(?P<ver>[^-]+)\.factory\.bin$")


def api(path):
    repo = os.environ["GITHUB_REPOSITORY"]                       # "owner/repo", set by Actions
    req = urllib.request.Request(f"{API}/repos/{repo}{path}")
    tok = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN")
    if tok:
        req.add_header("Authorization", f"Bearer {tok}")
    req.add_header("Accept", "application/vnd.github+json")
    with urllib.request.urlopen(req) as r:
        return json.load(r)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--registry", default="site/boards.json")
    ap.add_argument("--out", default="site/firmware/versions.json")
    ap.add_argument("--url-prefix", default=None, help="same-origin prefix; else the Release asset URL")
    a = ap.parse_args()

    reg = json.load(open(a.registry, encoding="utf-8")).get("boards", {})
    boards = {bid: {"label": m["label"], "photo": m["photo"], "versions": []} for bid, m in reg.items()}

    # GitHub returns releases newest-first -> versions[] stays newest-first, "latest" = versions[0].
    for rel in api("/releases?per_page=100"):
        if rel.get("draft"):
            continue
        for asset in rel.get("assets", []):
            m = ASSET_RE.match(asset["name"])
            if not m or m.group("id") not in boards:
                continue
            url = f'{a.url_prefix}/{asset["name"]}' if a.url_prefix else asset["browser_download_url"]
            boards[m.group("id")]["versions"].append(
                {"version": m.group("ver"), "url": url, "size": asset.get("size")}
            )

    out = {
        "_note": "Generated by .github/scripts/gen_versions_json.py from the board registry + GitHub Releases. Do not edit by hand.",
        "boards": boards,
    }
    os.makedirs(os.path.dirname(a.out) or ".", exist_ok=True)
    with open(a.out, "w", encoding="utf-8") as f:
        json.dump(out, f, indent=2)
    n = sum(len(b["versions"]) for b in boards.values())
    print(f"wrote {a.out}: {len(boards)} board(s), {n} version(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
