"""Per-board banner-asset generator - one run emits every artifact derived from a board's baked set, from the
single source of truth in board_assets.yaml. Replaces gen_web_banners.py (+ its full/minimal split) and the
hand-synced presets_tdisplay_extra.yaml / banner_preset_{full,minimal}.yaml / WD_BAKED_JSON / WD_BAKE_MINIMAL.

Per board <b>, from board_assets.yaml boards.<b>:
  web    -> esphome/banners_baked_<b>.h            (WebP bytes + ENTRIES[] table; web_dashboard.h serves
                                                    /img/<name> and builds /gallery baked[] by iterating ENTRIES)
  screen -> esphome/packages/presets_<b>.yaml       (image: dash+saver at the board's resize; empty on screenless)
            esphome/packages/banner_preset_<b>.yaml (select options = web+Custom; lookup chains from screen)

Invariants (docs/internal/gen-board-assets-plan.md): the lookup chain names ONLY screen presets (config-time
id() safety); screenless => no image entries; canonical append-only order (NVS index restore); hard-fail on a
missing source webp or an over-budget baked set.

Run:  python esphome/tools/gen_board_assets.py [--board <id> | --all] [--out-dir DIR] [--check]
Then: python esphome/tools/gen_dashboard_h.py   (web pages are separate, board-agnostic)
"""
import argparse
import io
import pathlib
import sys

import yaml
from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parents[2]
IMG = ROOT / "esphome" / "images"
CONFIG = pathlib.Path(__file__).resolve().parent / "board_assets.yaml"

# Web hero render params - VERBATIM from gen_web_banners.py so output is byte-identical to today's headers.
WEB_MAXH = 160
WEB_MAXW = 340
WEBP_Q = 82


def src_file(name):
    return f"{name.lower()}.webp"          # "SUV" -> suv.webp, "Battery" -> battery.webp


def img_id(name, saver=False):
    return f"preset_{name.lower()}{'_saver' if saver else ''}_img"


def render_web(path):
    """Crop to content, downscale to web hero size, re-encode WebP -> raw bytes. (verbatim: gen_web_banners.py)"""
    im = Image.open(path).convert("RGBA")
    bbox = im.getbbox()
    if bbox:
        im = im.crop(bbox)
    scale = min(WEB_MAXW / im.width, WEB_MAXH / im.height)
    tw, th = max(1, round(im.width * scale)), max(1, round(im.height * scale))
    im = im.resize((tw, th), Image.LANCZOS)
    buf = io.BytesIO()
    im.save(buf, format="WEBP", quality=WEBP_Q, method=6)
    return buf.getvalue(), im.size


def c_array(name, data):
    body = []
    for i in range(0, len(data), 20):
        body.append("  " + ",".join(str(b) for b in data[i:i + 20]) + ",")
    return f"static const uint8_t IMG_{name}[] = {{\n" + "\n".join(body) + f"\n}};  // {len(data)} B\n"


def build_web_header(names):
    """banners_baked_<board>.h for the board's `web` list. Same namespace/API/format as the old
    gen_web_banners.py -> byte-identical arrays; hard-fails on a missing source (was a silent skip)."""
    lines = [
        "#pragma once",
        "// GENERATED by esphome/tools/gen_board_assets.py from board_assets.yaml - DO NOT EDIT.",
        "// Web-quality WebP bytes for this board's baked banner presets, served from flash by",
        "// web_dashboard.h BannerBakedGet at GET /img/<name>. Device on-screen bake is separate",
        "// (esphome/images/*.webp -> LVGL RGB565A8 per board). Regen: python esphome/tools/gen_board_assets.py",
        "#include <cstdint>",
        "#include <cstddef>",
        "#include <cstring>",
        "namespace esphome {",
        "namespace banners_baked {",
        "",
    ]
    entries, total, report = [], 0, []
    for name in names:
        path = IMG / src_file(name)
        if not path.exists():
            sys.exit(f"ERROR: source webp missing for '{name}': {path}")
        data, size = render_web(path)
        total += len(data)
        lines.append(c_array(name, data))
        entries.append((name, f"IMG_{name}"))
        report.append((name, size, len(data)))
    lines.append("struct Entry { const char *name; const uint8_t *data; size_t len; };")
    lines.append("static const Entry ENTRIES[] = {")
    for name, sym in entries:
        lines.append(f'  {{"{name}", {sym}, sizeof({sym})}},')
    lines.append("};")
    lines += [
        "",
        "// Look up a preset's WebP bytes by name (from the /img/<name> URL). null if unknown.",
        "inline const uint8_t *webp(const char *name, size_t &len) {",
        "  for (const auto &e : ENTRIES)",
        "    if (strcmp(e.name, name) == 0) { len = e.len; return e.data; }",
        "  return nullptr;",
        "}",
        "",
        "}  // namespace banners_baked",
        "}  // namespace esphome",
    ]
    return "\n".join(lines) + "\n", total, report


def _img_entry(name, saver, w, h):
    return (f"  - file: images/{src_file(name)}\n"
            f"    id: {img_id(name, saver)}\n"
            f"    type: RGB\n"
            f"    transparency: alpha_channel\n"
            f"    resize: {w}x{h}\n")


def build_presets_yaml(board, bid):
    """image: dash entries (all) then saver entries (all), for screen presets MINUS Battery (Battery's image
    lives in display_tdisplay.yaml). Returns None when there are no non-Battery presets (screenless / Battery-only)
    -> no file emitted + the master includes no presets package (matches today's 4mb/headless)."""
    extra = [n for n in board["screen"] if n != "Battery"]
    if not extra:
        return None
    head = (f"# GENERATED by esphome/tools/gen_board_assets.py from board_assets.yaml[{bid}] - DO NOT EDIT.\n"
            f"# On-screen LVGL bakes for this board's `screen` set (dash {board['dash']}, saver {board['saver']}).\n")
    dw, dh = board["dash"]
    sw, sh = board["saver"]
    body = "".join(_img_entry(n, False, dw, dh) for n in extra) + "".join(_img_entry(n, True, sw, sh) for n in extra)
    return head + "image:\n" + body


def build_banner_preset_yaml(board, bid):
    """The banner_preset template select (options = web list + Custom) + the lookup-chain substitutions
    (derived STRICTLY from `screen` minus Battery, so no id() names a preset this board doesn't bake)."""
    extra = [n for n in board["screen"] if n != "Battery"]

    def chain(var, dst, suffix):
        if not extra:
            return f'  {var}: ""'
        parts = []
        for i, n in enumerate(extra):
            kw = "if" if i == 0 else "else if"
            parts.append(f'    {kw} ({dst} == "{n}") {suffix} = id({img_id(n, suffix == "sv")});')
        return f"  {var}: |-\n" + "\n".join(parts)

    opts = "\n".join(f'      - "{n}"' for n in board["web"]) + '\n      - "Custom"'
    return (
        f"# GENERATED by esphome/tools/gen_board_assets.py from board_assets.yaml[{bid}] - DO NOT EDIT.\n"
        f"# banner_preset picker (options = web set + Custom) + the on-screen lookup chains (screen set).\n"
        f"# The select id is defined ONCE here (per board). Order is canonical/append-only (NVS index restore).\n"
        "substitutions:\n"
        f"{chain('banner_dash_lookup', 'bp', 'bimg')}\n"
        f"{chain('banner_saver_lookup', 'sbp', 'sv')}\n"
        "\n"
        "select:\n"
        "  - platform: template\n"
        "    id: banner_preset\n"
        '    name: "Banner preset"\n'
        "    disabled_by_default: true\n"
        "    optimistic: true\n"
        "    restore_value: true\n"
        "    options:\n"
        f"{opts}\n"
        '    initial_option: "Battery"\n'
    )


def screen_flash_bytes(board):
    """On-screen app-flash contribution: each screen preset (minus Battery, already in the display package)
    = dash w*h*3 + saver w*h*3 (RGB565A8 rodata, 3 B/px). The dominant 4 MB-slot lever."""
    extra = [n for n in board["screen"] if n != "Battery"]
    if not extra or not board["dash"]:
        return 0
    per = board["dash"][0] * board["dash"][1] * 3 + board["saver"][0] * board["saver"][1] * 3
    return per * len(extra)


def gen_board(bid, board, out_dir, check):
    header, web_total, web_report = build_web_header(board["web"])
    presets = build_presets_yaml(board, bid)
    picker = build_banner_preset_yaml(board, bid)

    scr = screen_flash_bytes(board)
    contrib = scr + web_total
    print(f"[{bid}] web={board['web']!r}")
    print(f"         screen={board['screen']!r} dash={board['dash']} saver={board['saver']}")
    for name, size, nb in web_report:
        print(f"           web {name:11s} {size}  {nb/1024:.1f} KB")
    print(f"         on-screen flash = {scr:,} B | web flash = {web_total:,} B | baked contribution = {contrib:,} B")
    budget = board.get("budget")
    if budget is not None and contrib > budget:
        sys.exit(f"ERROR: [{bid}] baked set {contrib:,} B exceeds budget {budget:,} B")

    targets = {
        out_dir / "esphome" / f"banners_baked_{bid}.h": header,
        out_dir / "esphome" / "packages" / f"banner_preset_{bid}.yaml": picker,
    }
    if presets is not None:   # only boards with non-Battery on-screen presets get a presets package
        targets[out_dir / "esphome" / "packages" / f"presets_{bid}.yaml"] = presets
    drift = False
    for path, content in targets.items():
        if check:
            cur = path.read_text(encoding="utf-8") if path.exists() else ""
            ok = cur == content
            drift = drift or not ok
            print(("  OK   " if ok else "  DIFF ") + str(path.relative_to(out_dir)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"  wrote {path.relative_to(out_dir)}")
    return drift


def main():
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--board")
    g.add_argument("--all", action="store_true")
    ap.add_argument("--out-dir", default=str(ROOT), help="write under this root instead of the repo (for diffing)")
    ap.add_argument("--check", action="store_true", help="don't write; report OK/DIFF vs existing files")
    args = ap.parse_args()
    out_dir = pathlib.Path(args.out_dir)
    boards = yaml.safe_load(CONFIG.read_text(encoding="utf-8"))["boards"]
    ids = [args.board] if args.board else list(boards)
    drift = False
    for bid in ids:
        drift = gen_board(bid, boards[bid], out_dir, args.check) or drift
    if args.check and drift:
        sys.exit("ERROR: generated assets are out of date — run `python esphome/tools/gen_board_assets.py --all`")


if __name__ == "__main__":
    main()
