"""Generate web-quality banner WebP bytes and bake them into esphome/banners_baked.h.

The device (TTGO) uses the tiny compiled preset-*.png (LVGL RGB565A8); the web hero deserves crisp
art, so we re-render each vehicle from esphome/images/*.webp at ~1.5x hero height, re-encode to WebP
(lossy, with alpha), and emit the raw bytes as a C header. web_dashboard.h's BannerBakedGet serves
each at GET /img/<name> (image/webp, long cache) so the browser fetches each once. The device never
touches these bytes.

WHY a header instead of base64 in the page: the 10 presets inlined as base64 made web/dashboard.html
~255KB (66% was the base64 blob). Serving that one huge contiguous response OOM-crashed the no-PSRAM
board (heap fragmentation). De-inlining drops the page to ~90KB and each banner is a tiny mmap'd/rodata
response.

Run: python esphome/tools/gen_web_banners.py   (then: python esphome/tools/gen_dashboard_h.py)
"""
import io
import pathlib

from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parents[2]  # repo root (esphome/tools/ -> ../../)
IMG = ROOT / "esphome" / "images"
OUT = ROOT / "esphome" / "banners_baked.h"              # full 10 presets — 16MB T-Display + headless
OUT_MIN = ROOT / "esphome" / "banners_baked_minimal.h"  # Battery only — 4MB T-Display (web matches the LCD bake-1)

WEB_MAXH = 160     # ~1.6x the 96px hero .car height (crisp enough, keeps the bytes small)
WEB_MAXW = 340     # keep wide subjects (boat) inside the hero card
WEBP_Q = 82        # lossy quality; illustrations stay clean, size drops hard

# preset name -> source file. Order/names mirror the banner_preset select (Battery first = default).
# Sources are the transparent WebP cut-outs the converter produced, dropped into esphome/images/.
SOURCES = {
    "Battery": IMG / "battery.webp",
    "Sedan": IMG / "sedan.webp",
    "SUV": IMG / "suv.webp",
    "Pickup": IMG / "pickup.webp",
    "Van": IMG / "van.webp",
    "Classic": IMG / "classic.webp",
    "Sports": IMG / "sports.webp",
    "Quad": IMG / "quad.webp",
    "Motorcycle": IMG / "motorcycle.webp",
    "Boat": IMG / "boat.webp",
}


def render_web(path):
    """Crop to content, downscale to web hero size, re-encode WebP -> raw bytes."""
    im = Image.open(path).convert("RGBA")
    bbox = im.getbbox()
    if bbox:
        im = im.crop(bbox)
    scale = min(WEB_MAXW / im.width, WEB_MAXH / im.height)
    tw, th = max(1, round(im.width * scale)), max(1, round(im.height * scale))
    im = im.resize((tw, th), Image.LANCZOS)
    buf = io.BytesIO()
    im.save(buf, format="WEBP", quality=WEBP_Q, method=6)
    return buf.getvalue(), im.size


def c_array(name, data):
    body = []
    for i in range(0, len(data), 20):
        body.append("  " + ",".join(str(b) for b in data[i:i + 20]) + ",")
    return f"static const uint8_t IMG_{name}[] = {{\n" + "\n".join(body) + f"\n}};  // {len(data)} B\n"


def build(sources, out_path):
    """Emit one banners_baked header for the given {name: webp-source} set. Same namespace/API for every set,
    so a board picks the full or the minimal header via the WD_BAKE_MINIMAL include switch in web_dashboard.h."""
    lines = [
        "#pragma once",
        "// GENERATED by esphome/tools/gen_web_banners.py — DO NOT EDIT.",
        "// Web-quality WebP bytes for the baked banner presets, served from flash by",
        "// web_dashboard.h BannerBakedGet at GET /img/<name>. De-inlined from web/dashboard.html to keep",
        "// the served page small (the base64 blob caused heap-exhaustion OOM). Device display is separate",
        "// (esphome/images/*.webp -> LVGL RGB565A8). Regen: python esphome/tools/gen_web_banners.py",
        "#include <cstdint>",
        "#include <cstddef>",
        "#include <cstring>",
        "namespace esphome {",
        "namespace banners_baked {",
        "",
    ]
    entries = []
    total = 0
    for name, path in sources.items():
        if not path.exists():
            print("MISSING", path.name)
            continue
        data, size = render_web(path)
        total += len(data)
        lines.append(c_array(name, data))
        entries.append((name, f"IMG_{name}"))
        print(f"{name:11s} -> {size}  ({len(data) / 1024:.1f} KB webp)")

    lines.append("struct Entry { const char *name; const uint8_t *data; size_t len; };")
    lines.append("static const Entry ENTRIES[] = {")
    for name, sym in entries:
        lines.append(f'  {{"{name}", {sym}, sizeof({sym})}},')
    lines.append("};")
    lines.append("")
    lines.append("// Look up a preset's WebP bytes by name (from the /img/<name> URL). null if unknown.")
    lines.append("inline const uint8_t *webp(const char *name, size_t &len) {")
    lines.append("  for (const auto &e : ENTRIES)")
    lines.append("    if (strcmp(e.name, name) == 0) { len = e.len; return e.data; }")
    lines.append("  return nullptr;")
    lines.append("}")
    lines.append("")
    lines.append("}  // namespace banners_baked")
    lines.append("}  // namespace esphome")

    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out_path.name}  ({len(entries)} banners, ~{total / 1024:.0f} KB webp bytes, header {out_path.stat().st_size // 1024} KB)")


def main():
    build(SOURCES, OUT)                                # full 10 — 16MB T-Display + headless (serves the whole gallery)
    build({"Battery": SOURCES["Battery"]}, OUT_MIN)    # Battery only — 4MB T-Display (picker offers Battery + Custom)


if __name__ == "__main__":
    main()
